chore(cdt): reverting old changes , not working

diff --git a/.local/bin/cdt b/.local/bin/cdt
--- a/.local/bin/cdt
+++ b/.local/bin/cdt
@@ -13,61 +13,49 @@ check_commands() {
     done
 }
 
-detach_and_create_new_session() {
-    local directory_path="$1"
-    local pane_name
-
-    pane_name=$(basename "$directory_path")
-
-    if tmux has-session -t "$pane_name" 2>/dev/null && [ -n "$directory_path" ]; then
-        tmux switch-client -t "$pane_name"
-    else
-        if [ -d "$directory_path" ]; then
-            if [ -z "$TMUX" ]; then
-                tmux new-session -s "$pane_name" -c "$directory_path"
-            else
-                tmux switch-client -t "$pane_name" || {
-                    echo "Can't find or switch to session: $pane_name"
-                    exit 1
-                }
-            fi
-        else
-            echo "Directory not found: $directory_path. Please check the path and try again."
-            exit 1
-        fi
-    fi
-}
-
+# Handle scenario when directory is specified
 handle_directory() {
     local directory="$1"
+    local directory_path
+    local pane_name
 
     if [ -n "$directory" ]; then
-        local directory_path=$(zoxide query "$directory")
-        detach_and_create_new_session "$directory_path"
+        directory_path=$(zoxide query "$directory")
+        pane_name=$(basename "$directory_path")
+
+        if tmux has-session -t "$pane_name" 2>/dev/null && [ -n "$directory_path" ]; then
+            tmux switch-client -t "$pane_name"
+        else
+            if [ -d "$directory_path" ]; then
+                builtin cd "$directory_path" || echo "Couldn't change directory"
+                tmux new-session -s "$pane_name" -c "$directory_path"
+            else
+                echo "Directory not found: $directory. Please check the path and try again."
+                exit 1
+            fi
+        fi
     else
         handle_no_directory
     fi
 }
 
+# Handle scenario when no directory is specified
 handle_no_directory() {
-    local available_sessions=$(tmux list-sessions -F "#{session_name}" 2>/dev/null | sort)
+    available_sessions=$(tmux list-sessions -F "#{session_name}" 2>/dev/null | sort)
 
     if [ -z "$available_sessions" ]; then
         echo "No sessions available. Specify a directory to open a new session."
         return
     fi
 
-    local selected_session=$(echo "$available_sessions" | fzf --prompt="  Available sessions " --height=35% --layout=reverse --border --exit-0)
+    selected_session=$(echo "$available_sessions" | fzf --prompt="  Available sessions " --height=35% --layout=reverse --border --exit-0)
 
     if [ -z "$selected_session" ]; then
         echo "No sessions selected."
         return
     fi
 
-    tmux switch-client -t "$selected_session" || {
-        echo "Can't find or switch to session: $selected_session"
-        exit 1
-    }
+    tmux attach-session -t "$selected_session"
 }
 
 main() {
